/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import util.ConectaBanco;

/**
 *
 * @author vinicius caetano
 */
public class Principal extends javax.swing.JFrame {
    
    ConectaBanco conectar = new ConectaBanco();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        conectar.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuEstado = new javax.swing.JMenuItem();
        MenuCidade = new javax.swing.JMenuItem();
        MenuBairro = new javax.swing.JMenuItem();
        MenuTelefone = new javax.swing.JMenuItem();
        MenuCliente = new javax.swing.JMenuItem();
        MenuFornecedores = new javax.swing.JMenuItem();
        MenuProdutos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Vendas");

        jMenu1.setText("Cadastro");

        MenuEstado.setText("Estados");
        MenuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEstadoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuEstado);

        MenuCidade.setText("Cidades");
        MenuCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCidadeActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCidade);

        MenuBairro.setText("Bairro");
        jMenu1.add(MenuBairro);

        MenuTelefone.setText("Telefones");
        jMenu1.add(MenuTelefone);

        MenuCliente.setText("Clientes");
        jMenu1.add(MenuCliente);

        MenuFornecedores.setText("Fornecedores");
        jMenu1.add(MenuFornecedores);

        MenuProdutos.setText("Produtos");
        jMenu1.add(MenuProdutos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Compra");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Venda");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatorio");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Sair");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        conectar.dseconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void MenuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEstadoActionPerformed
        // TODO add your handling code here:
        EstadoView ev = new EstadoView();
        ev.setVisible(true);
        
    }//GEN-LAST:event_MenuEstadoActionPerformed

    private void MenuCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCidadeActionPerformed
        // TODO add your handling code here:
        CidadeView cv = new CidadeView();
        cv.setVisible(true);
    }//GEN-LAST:event_MenuCidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuBairro;
    private javax.swing.JMenuItem MenuCidade;
    private javax.swing.JMenuItem MenuCliente;
    private javax.swing.JMenuItem MenuEstado;
    private javax.swing.JMenuItem MenuFornecedores;
    private javax.swing.JMenuItem MenuProdutos;
    private javax.swing.JMenuItem MenuTelefone;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
